name: formigas_mvc
description: Model-view-controller state management library for flutter, which we use here in our daily business at https://formigas.io
version: 1.0.0
homepage: https://formigas.io

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
